/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AstalashmiRouteImport } from './routes/astalashmi'
import { Route as DashavataraRouteImport } from './routes/dashavatara'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AstalashmiRoute = AstalashmiRouteImport.update({
  id: '/astalashmi',
  path: '/astalashmi',
  getParentRoute: () => rootRouteImport,
} as any)
const DashavataraRoute = DashavataraRouteImport.update({
  id: '/dashavatara',
  path: '/dashavatara',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/astalashmi': typeof AstalashmiRoute
  '/dashavatara': typeof DashavataraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/astalashmi': typeof AstalashmiRoute
  '/dashavatara': typeof DashavataraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/astalashmi': typeof AstalashmiRoute
  '/dashavatara': typeof DashavataraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/astalashmi' | '/dashavatara'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/astalashmi' | '/dashavatara'
  id: '__root__' | '/' | '/admin' | '/astalashmi' | '/dashavatara'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AstalashmiRoute: typeof AstalashmiRoute
  DashavataraRoute: typeof DashavataraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astalashmi': {
      id: '/astalashmi'
      path: '/astalashmi'
      fullPath: '/astalashmi'
      preLoaderRoute: typeof AstalashmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashavatara': {
      id: '/dashavatara'
      path: '/dashavatara'
      fullPath: '/dashavatara'
      preLoaderRoute: typeof DashavataraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AstalashmiRoute: AstalashmiRoute,
  DashavataraRoute: DashavataraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
